import logging
import time
from pathlib import Path

from fastapi import FastAPI, Request

from src.agents.langgraph_orchestrator import LangGraphDemandDecisionOrchestrator
from src.api.agentic_schema import PredictionRequest, PredictionResponse

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    filename=LOG_DIR / "agentic_api.log",
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

app = FastAPI(
    title="Agentic Intelligent Demand Forecasting API",
    version="1.0.0",
)

orchestrator = LangGraphDemandDecisionOrchestrator()


@app.middleware("http")
async def log_requests(request: Request, call_next):
    start_time = time.time()

    try:
        response = await call_next(request)
    except Exception as exc:
        process_time = round(time.time() - start_time, 4)
        logging.exception(
            "agentic_request_failed method=%s path=%s latency_seconds=%s error=%s",
            request.method,
            request.url.path,
            process_time,
            str(exc),
        )
        raise

    process_time = round(time.time() - start_time, 4)

    logging.info(
        "agentic_request_completed method=%s path=%s status_code=%s latency_seconds=%s",
        request.method,
        request.url.path,
        response.status_code,
        process_time,
    )

    return response


@app.get("/")
def home():
    return {
        "message": "Agentic Demand Forecasting API is running",
        "mode": "agentic",
        "agents": [
            "ForecastAgent",
            "TrendAnalysisAgent",
            "AnomalyDetectionAgent",
            "InventoryAgent",
        ],
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "mode": "agentic",
        "orchestrator": "DemandDecisionOrchestrator",
    }


@app.post("/predict", response_model=PredictionResponse)
def predict(request: PredictionRequest):
    request_data = request.model_dump()

    logging.info(
        "agentic_prediction_request store_id=%s item_id=%s date=%s price=%s promo=%s",
        request.store_id,
        request.item_id,
        request.date,
        request.price,
        request.promo,
    )

    try:
        decision_result = orchestrator.run(request_data)
    except Exception as exc:
        logging.exception(
            "agentic_prediction_failed store_id=%s item_id=%s date=%s error=%s",
            request.store_id,
            request.item_id,
            request.date,
            str(exc),
        )
        raise

    predicted_demand = decision_result["predicted_demand"]
    recommendation = decision_result["recommendation"]
    confidence_level = decision_result["confidence_level"]
    anomaly_warning = decision_result["anomaly_warning"]

    if predicted_demand > 100:
        logging.warning(
            "agentic_high_prediction_detected store_id=%s item_id=%s predicted_demand=%s",
            request.store_id,
            request.item_id,
            predicted_demand,
        )

    if predicted_demand < 0:
        logging.warning(
            "agentic_negative_prediction_detected store_id=%s item_id=%s predicted_demand=%s",
            request.store_id,
            request.item_id,
            predicted_demand,
        )

    forecast_summary = (
        f"Expected demand for {request.item_id} at {request.store_id} "
        f"on {request.date} is {predicted_demand}. "
        f"Recommended action: {recommendation}. "
        f"Decision generated by agentic orchestration."
    )

    logging.info(
        "agentic_prediction_response store_id=%s item_id=%s predicted_demand=%s "
        "recommendation=%s confidence_level=%s anomaly_warning=%s agents=%s",
        request.store_id,
        request.item_id,
        predicted_demand,
        recommendation,
        confidence_level,
        anomaly_warning,
        list(decision_result.get("agents", {}).keys()),
    )

    return PredictionResponse(
        store_id=request.store_id,
        item_id=request.item_id,
        forecast_date=request.date,
        predicted_demand=predicted_demand,
        recommendation=recommendation,
        confidence_level=confidence_level,
        anomaly_warning=anomaly_warning,
        trend=decision_result["trend"],
        trend_reason=decision_result["trend_reason"],
        anomaly_severity=decision_result["anomaly_severity"],
        forecast_summary=forecast_summary,
        model_name="Agentic LightGBM Demand Forecasting System",
        model_version="1.0.0",
    )
